# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestingApp
pod 'SampleFramework', :path => "../SampleFramework/"
  target 'TestingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingAppUITests' do
    # Pods for testing
  end

end
